repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        language: system
        entry: bash -c "flake8 --exclude .venv"
        pass_filenames: false
        always_run: true
      - id: ruff
        name: ruff
        language: system
        entry: bash -c "ruff check"
        pass_filenames: false
        always_run: true
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
